#!/usr/bin/env bash
# Step 03: generate config.toml and config.taker.toml from the environment.
#
# Writes nothing outside the repo and sends no transaction. Both generated
# files hold addresses and URLs only; keys stay in .env and are read from the
# environment at run time.
#
#   scripts/deploy/03_write_config.sh                  # write both
#   scripts/deploy/03_write_config.sh --check          # diff against what exists
#   scripts/deploy/03_write_config.sh --coordinator    # coordinator config only
#   scripts/deploy/03_write_config.sh --taker          # taker config only
#
# Idempotent: writing the same environment twice produces the same file. The
# generated files are gitignored, because they name a specific deployment.
#
# Env: everything from .env, plus GLUE_CONTRACT_ADDRESS from step 01.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
. "$ROOT/scripts/deploy/lib.sh"
load_deployed

CHECK=""; DO_COORD=1; DO_TAKER=1
for a in "$@"; do
  case "$a" in
    --check) CHECK=1;;
    --coordinator) DO_TAKER=0;;
    --taker) DO_COORD=0;;
    --help|-h) sed -n '2,20p' "$0"; exit 0;;
  esac
done

COORD_OUT="${COORDINATOR_CONFIG_PATH:-$ROOT/config.generated.toml}"
TAKER_OUT="${TAKER_CONFIG_PATH:-$ROOT/config.taker.generated.toml}"

require_address GLUE_CONTRACT_ADDRESS
require_address USDC_ADDRESS
require_address ZKP2P_ESCROW_ADDRESS
require_address ZKP2P_ORCHESTRATOR_ADDRESS
require_address STAKE_VAULT_ADDRESS
require_address ATTESTATION_VERIFIER_ADDRESS

SERVER_HOST="${COORDINATOR_HOST:-127.0.0.1}"
SERVER_PORT="${COORDINATOR_PORT:-3000}"
DB_PATH="${DATABASE_PATH:-zecp2p.db}"
KEEPER_POLL="${KEEPER_POLL_INTERVAL_SECONDS:-15}"
NEAR_TIMEOUT="${NEAR_DEFAULT_TIMEOUT:-600}"
TAKER_MAX="${TAKER_MAX_INTENT_AMOUNT:-100000000}"
TAKER_MIN="${TAKER_MIN_INTENT_AMOUNT:-1000000}"
TAKER_POLL="${TAKER_POLL_INTERVAL_SECONDS:-15}"
TAKER_LOOKBACK="${TAKER_LOOKBACK_BLOCKS:-5000}"
VENMO_CDP="${VENMO_CDP_URL:-http://127.0.0.1:9222}"
VENMO_NOTE="${VENMO_NOTE:-thanks}"

# The header carries the time the file was written, which changes on every run
# and says nothing about the configuration. --check compares the settings, so it
# drops that line from both sides before diffing; otherwise a check run one
# second after a write reports a difference that is not one.
strip_stamp() { sed '/^# Generated by scripts\/deploy\/03_write_config.sh on /d' "$1"; }

write_or_check() { # path, content-on-stdin
  local path="$1" tmp
  tmp="$(mktemp)"
  cat > "$tmp"
  if [ -n "$CHECK" ]; then
    if [ -f "$path" ] && diff -q <(strip_stamp "$path") <(strip_stamp "$tmp") >/dev/null 2>&1; then
      ok "$(basename "$path") matches the current environment"
    else
      bad "$(basename "$path") differs from the current environment:"
      diff -u <(strip_stamp "${path:-/dev/null}") <(strip_stamp "$tmp") 2>/dev/null \
        | sed 's/^/    /' | head -40 || true
      rm -f "$tmp"; return 1
    fi
    rm -f "$tmp"
  else
    mv "$tmp" "$path"
    ok "wrote $path"
  fi
}

RC=0

if [ "$DO_COORD" = 1 ]; then
log "coordinator config"
write_or_check "$COORD_OUT" <<EOF || RC=1
# Generated by scripts/deploy/03_write_config.sh on $(date -Iseconds).
# Do not hand-edit: change .env and re-run the script.
# Addresses and URLs only. Keys come from the environment at run time
# (COORDINATOR_PRIVATE_KEY), never from this file.

[network]
base_rpc_url = "$BASE_RPC_URL"
chain_id = $CHAIN_ID

[contracts]
usdc = "$USDC_ADDRESS"
zkp2p_escrow = "$ZKP2P_ESCROW_ADDRESS"
zkp2p_orchestrator = "$ZKP2P_ORCHESTRATOR_ADDRESS"
stake_vault = "$STAKE_VAULT_ADDRESS"
glue_contract = "$GLUE_CONTRACT_ADDRESS"

[near]
api_url = "$NEAR_API_URL"
default_timeout = $NEAR_TIMEOUT

[zkp2p]
api_url = "$ZKP2P_API_URL"

[attestation]
service_url = "$ATTESTATION_URL"
verifier = "$ATTESTATION_VERIFIER_ADDRESS"

[keeper]
poll_interval_seconds = $KEEPER_POLL
session_timeout_seconds = ${KEEPER_SESSION_TIMEOUT_SECONDS:-3600}
# 1Click keeps a deposit address live for about three days and refunds an
# under-deposit by that deadline, so a session still awaiting ZEC gets longer.
near_intent_timeout_seconds = ${KEEPER_NEAR_TIMEOUT_SECONDS:-302400}
event_lookback_blocks = ${KEEPER_EVENT_LOOKBACK_BLOCKS:-1000}

[server]
host = "$SERVER_HOST"
port = $SERVER_PORT

[database]
path = "$DB_PATH"
EOF
fi

if [ "$DO_TAKER" = 1 ]; then
log "taker config"
write_or_check "$TAKER_OUT" <<EOF || RC=1
# Generated by scripts/deploy/03_write_config.sh on $(date -Iseconds).
# Do not hand-edit: change .env and re-run the script.
# The taker key comes from TAKER_PRIVATE_KEY in the environment, not from here.

[network]
base_rpc_url = "$BASE_RPC_URL"
chain_id = $CHAIN_ID

[contracts]
usdc = "$USDC_ADDRESS"
zkp2p_escrow = "$ZKP2P_ESCROW_ADDRESS"
zkp2p_orchestrator = "$ZKP2P_ORCHESTRATOR_ADDRESS"
stake_vault = "$STAKE_VAULT_ADDRESS"
glue_contract = "$GLUE_CONTRACT_ADDRESS"

[taker]
coordinator_url = "http://$SERVER_HOST:$SERVER_PORT"
# 6-decimal USDC units. Each intent locks this much stake as well as costing
# the taker the same amount in real dollars on Venmo.
max_intent_amount = "$TAKER_MAX"
min_intent_amount = "$TAKER_MIN"
poll_interval_seconds = $TAKER_POLL
lookback_blocks = $TAKER_LOOKBACK

[venmo]
cdp_url = "$VENMO_CDP"
note = "$VENMO_NOTE"
timeout_seconds = ${VENMO_TIMEOUT_SECONDS:-120}

[attestation]
service_url = "$ATTESTATION_URL"
verifier = "$ATTESTATION_VERIFIER_ADDRESS"
EOF
fi

echo
if [ "$RC" != 0 ]; then
  echo "config on disk does not match the environment. Re-run without --check to regenerate."
  exit 1
fi

if [ -z "$CHECK" ]; then
  echo "Run the coordinator with:"
  echo "  ZECP2P_CONFIG=$COORD_OUT cargo run --release --bin zecp2p-coordinator"
  echo "Run the taker agent with:"
  echo "  ZECP2P_TAKER_CONFIG=$TAKER_OUT cargo run --release --bin zecp2p-taker -- agent"
  echo
  echo "Next: scripts/deploy/04_verify_near_leg.sh"
fi
